export { default as CloseIcon } from "./Icons/Close";
export { default as AvalancheFillIcon } from "./Icons/AvalancheBadgeFill";
export { default as LockIcon } from "./Icons/Lock";

export { default as TwitterIcon } from "./Icons/twitter";
export { default as DiscordIcon } from "./Icons/discord";
export { default as TelegramIcon } from "./Icons/telegram";
export { default as GithubIcon } from "./Icons/GithubIcon";
export { default as MediumIcon } from "./Icons/medium";
export { default as MetamaskIcon } from "./Icons/Metamask";

export { default as ClockDarkIcon } from "./Icons/ClockDark";
export { default as LinkIcon } from "./Icons/Link";
export { default as ScheduleIcon } from "./Icons/Schedule";
export { default as TetherIcon } from "./Icons/tether";
export { default as USDCoinIcon } from "./Icons/usd-coin";
export { default as TerraUSDIcon } from "./Icons/terra-usd";
export { default as BinanceUSDIcon } from "./Icons/binance-usd";
export { default as DIAIcon } from "./Icons/dai";
export { default as FacebookIcon } from "./Icons/ProjectsFacebook";
export { default as ProjectsInstaIcon } from "./Icons/ProjectsInsta";

export { default as InfoIcon } from "./Icons/InfoIcon";
export { default as FailureIcon } from "./Icons/FailureIcon";

export { default as BNBIcon } from "./Icons/BnbIcon";
export { default as AvaxIcon } from "./Icons/AvaxIcon";
export { default as FTMIcon } from "./Icons/FTMIcon";
export { default as EthIcon } from "./Icons/EthIcon";
export { default as EthIconWhite } from "./Icons/EthIconWhite";
export { default as SolanaWhite } from "./Icons/SolanaWhite";
export { default as AvalancheIconWhite } from "./Icons/AvalancheIconWhite";

export { default as WalletIcon } from "./Icons/Wallet";
export { default as CircleCheckedIcon } from "./Icons/CircleChecked";
export { default as CheckedIcon } from "./Icons/Checked";
export { default as DisconnectIcon } from "./Icons/DisconnectIcon";
export { default as CopyIcon } from "./Icons/CopyIcon";
export { default as SettledIcon } from "./Icons/settled";
export { default as AbortedIcon } from "./Icons/Aborted";
export { default as FireIcon } from "./Icons/Fire";
export { default as LoaderIcon } from "./Icons/Loader";
export { default as MenuIcon } from "./Icons/MenuIcon";
export { default as MoonIcon } from "./Icons/Moon";
export { default as SunIcon } from "./Icons/Sun";
export { default as ChevronIcon } from "./Icons/ChevronIcon";
export { default as EnvelopIcon } from "./Icons/EnvelopIcon";
export { default as ForbidIcon } from "./Icons/ForbidIcon";

export { default as MediumBoxIcon } from "./Icons/MediumBox";
export { default as TweeterBboxIcon } from "./Icons/TweeterBox";
export { default as CrossChainIcon } from "./Icons/CrossChain";
export { default as TelegramBoxIcon } from "./Icons/TelegramBox";
export { default as DiscrodBoxIcon } from "./Icons/DiscrodBox";
export { default as DecentralizedIcon } from "./Icons/Decentralized";
export { default as SecuredIcon } from "./Icons/Secured";

export { default as SolanaBadgeIcon } from "./Icons/SolanaBadge";
export { default as PolygonBadgeIcon } from "./Icons/PolygonBadge";
export { default as EthereumBadgeIcon } from "./Icons/EtherrumBadge";
export { default as BinanceBadgeIcon } from "./Icons/BinanceBadge";
export { default as FantomBadgeIcon } from "./Icons/FantomBadge";
export { default as AvalancheBadgeIcon } from "./Icons/AvalancheBadge";
export { default as UploadIcon } from "./Icons/Upload";
export { default as FileIcon } from "./Icons/FileIcon";
export { default as DeleteIcon } from "./Icons/DeleteIcon";
export { default as SpinerIcon } from "./Icons/Spinner";
export { default as CrossIcon } from "./Icons/CrossIcon";
export { default as VerifyKYCIcon } from "./Icons/VerifyKYC";
export { default as Success } from "./Icons/Success";
export { default as PendingIcon } from "./Icons/Pending";
export { default as BlockIcon } from "./Icons/Block";
export { default as InfoIn } from "./Icons/Info";
export { default as WarningIcon } from "./Icons/Warning";
export { default as TickCon } from "./Icons/Tick";
export { default as LockCon } from "./Icons/LockIcon";
export { default as AlertIcon } from "./Icons/AlertIcon";
export { default as RightIcon } from "./Icons/Right";
export { default as LeftIcon } from "./Icons/Left";
//Chains
export { default as AvaxChainIcon } from "./Icons/Chains/Avalanche";
export { default as OasisChainIcon } from "./Icons/Chains/Oasis";
export { default as FantomChainIcon } from "./Icons/Chains/Fantom";
export { default as SolanaChainIcon } from "./Icons/Chains/Solana";
export { default as EthChainIcon } from "./Icons/Chains/Ethereum";
export { default as PolygonChainIcon } from "./Icons/Chains/Polygon";
export { default as ArbitrumChainIcon } from "./Icons/Chains/Arbitrum";
export { default as OptimismChainIcon } from "./Icons/Chains/Optimism";
export { default as ErrorContribution } from "./Icons/error-contribution";
export { default as WalletAddressIcon } from "./Icons/walletIcon";
export { default as BaseChainIcon } from './Icons/Chains/Base'
